version: '3.1'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  nodeapp:
    build : .
    environment: 
    - PORT=3000
    depends_on: 
    - mongo

  mongo:
    image: mongo
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=shivam
     - MONGO_INITDB_ROOT_PASSWORD=mypasswd
    ports: 
    - "27016:27017"
    volumes:
     - mongo-db:/data/db
  redis:
    image: redis
volumes:
 mongo-db:

