version: '3.1'
services: 
  nodeapp:
    build : .
    ports:
    - "4001:5000"
    environment: 
    - PORT=5000
    depends_on: 
    - mongo

  mongo:
    image: mongo
    environment: 
     - MONGO_INITDB_ROOT_USERNAME=shivam
     - MONGO_INITDB_ROOT_PASSWORD=mypasswd
    ports: 
    - "27017:27017"
    volumes:
     - mongo-db:/data/db
  redis:
    image: redis
volumes:
 mongo-db:

